from enum import Enum

class State(str, Enum):
    NEW="NEW"; SCOPING="SCOPING"; DISCOVERING="DISCOVERING"; COLLECTING="COLLECTING"
    ANALYZING="ANALYZING"; CORRELATING="CORRELATING"; PLANNED="PLANNED"
    IMPACT_ANALYSIS="IMPACT_ANALYSIS"; AWAITING_APPROVAL="AWAITING_APPROVAL"
    IMPLEMENTING="IMPLEMENTING"; IMPLEMENTED_NOT_VERIFIED="IMPLEMENTED_NOT_VERIFIED"
    VERIFYING="VERIFYING"; REVIEWING="REVIEWING"; VERIFIED="VERIFIED"; COMPLETED="COMPLETED"
    BLOCKED="BLOCKED"; FAILED="FAILED"; ROLLING_BACK="ROLLING_BACK"; ROLLED_BACK="ROLLED_BACK"

ALLOWED = {
 State.NEW:{State.SCOPING,State.BLOCKED},
 State.SCOPING:{State.DISCOVERING,State.BLOCKED},
 State.DISCOVERING:{State.COLLECTING,State.BLOCKED,State.FAILED},
 State.COLLECTING:{State.ANALYZING,State.BLOCKED,State.FAILED},
 State.ANALYZING:{State.CORRELATING,State.BLOCKED,State.FAILED},
 State.CORRELATING:{State.PLANNED,State.BLOCKED,State.FAILED},
 State.PLANNED:{State.VERIFYING,State.IMPACT_ANALYSIS,State.BLOCKED},
 State.IMPACT_ANALYSIS:{State.AWAITING_APPROVAL,State.IMPLEMENTING,State.BLOCKED},
 State.AWAITING_APPROVAL:{State.IMPLEMENTING,State.BLOCKED},
 State.IMPLEMENTING:{State.IMPLEMENTED_NOT_VERIFIED,State.ROLLING_BACK,State.FAILED},
 State.IMPLEMENTED_NOT_VERIFIED:{State.VERIFYING,State.ROLLING_BACK,State.BLOCKED},
 State.VERIFYING:{State.REVIEWING,State.IMPLEMENTED_NOT_VERIFIED,State.ROLLING_BACK,State.FAILED},
 State.REVIEWING:{State.VERIFIED,State.IMPLEMENTED_NOT_VERIFIED,State.BLOCKED},
 State.VERIFIED:{State.COMPLETED},
 State.ROLLING_BACK:{State.ROLLED_BACK,State.FAILED},
}
def transition(current: State, target: State) -> State:
    if target not in ALLOWED.get(current,set()):
        raise ValueError(f"Invalid transition: {current} -> {target}")
    return target
